"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['reversal_ai.py']
DATA_FILES = ['light_wood.jpg']
OPTIONS = {
    'packages': ['numpy', 'pygame', 'sys', 'math','random']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
